SET @query = CONCAT(
  'GRANT ALL PRIVILEGES ON phpmyadmin.* TO  "',@PMA_USERNAME,
  '"@"%" IDENTIFIED BY "',@PMA_PASSWORD,'" WITH GRANT OPTION'
);
PREPARE stmt FROM @query; EXECUTE stmt; DEALLOCATE PREPARE stmt;
FLUSH PRIVILEGES;
