#!/bin/bash

if [ -n ${MYSQL_ENV_MYSQL_ROOT_PASSWORD+x} ]; then
  MYSQL_USERNAME=root
  MYSQL_PASSWORD="$MYSQL_ENV_MYSQL_ROOT_PASSWORD"
fi

mysql --host=$MYSQL_PORT_3306_TCP_ADDR --port=$MYSQL_PORT_3306_TCP_PORT --user=$MYSQL_USERNAME --password=$MYSQL_PASSWORD < /www/sql/create_tables.sql
mysql --host=$MYSQL_PORT_3306_TCP_ADDR --port=$MYSQL_PORT_3306_TCP_PORT --user=$MYSQL_USERNAME --password=$MYSQL_PASSWORD \
  -e "set @PMA_USERNAME='${PMA_USERNAME}', @PMA_PASSWORD='${PMA_PASSWORD}'; source /create_user.sql;"

cp /config.inc.php /www

sed -i \
    -e "s|\$PMA_SECRET|$PMA_SECRET|g" \
    -e "s|\$PMA_USERNAME|$PMA_USERNAME|g" \
    -e "s|\$PMA_PASSWORD|$PMA_PASSWORD|g" \
    -e "s|\$PMA_URI|$PMA_URI|g" \
    -e "s|\$MYSQL_PORT_3306_TCP_ADDR|$MYSQL_PORT_3306_TCP_ADDR|g" \
    -e "s|\$MYSQL_PORT_3306_TCP_PORT|$MYSQL_PORT_3306_TCP_PORT|g" \
    /www/config.inc.php
