#!/bin/sh

# wait for db to start accepting connections
while ! curl -s http://${MYSQL_PORT_3306_TCP_ADDR}:${MYSQL_PORT_3306_TCP_PORT}/ > /dev/null; do
    echo 'phpMyAdmin waiting for db to accept connections...'
    sleep 2
done

/usr/local/bin/phpmyadmin-setup

service php5-fpm start

exec nginx -g "daemon off;"
